DROP TABLE `activations`;--> statement-breakpoint
DROP TABLE `affiliate_settings`;--> statement-breakpoint
DROP TABLE `api_keys`;--> statement-breakpoint
DROP TABLE `apiLogs`;--> statement-breakpoint
DROP TABLE `balance_transactions`;--> statement-breakpoint
DROP TABLE `countries`;--> statement-breakpoint
DROP TABLE `customer_favorites`;--> statement-breakpoint
DROP TABLE `customer_sessions`;--> statement-breakpoint
DROP TABLE `customers`;--> statement-breakpoint
DROP TABLE `menu_items`;--> statement-breakpoint
DROP TABLE `operators`;--> statement-breakpoint
DROP TABLE `payment_settings`;--> statement-breakpoint
DROP TABLE `pix_transactions`;--> statement-breakpoint
DROP TABLE `priceHistory`;--> statement-breakpoint
DROP TABLE `prices`;--> statement-breakpoint
DROP TABLE `referral_earnings`;--> statement-breakpoint
DROP TABLE `referrals`;--> statement-breakpoint
DROP TABLE `services`;--> statement-breakpoint
DROP TABLE `settings`;--> statement-breakpoint
DROP TABLE `sms_apis`;--> statement-breakpoint
DROP TABLE `sms_messages`;--> statement-breakpoint
DROP TABLE `stripe_transactions`;