/**
 * Mapeamento oficial de códigos de serviços SMSHub para nomes legíveis
 * Extraído de: https://smshub.org/en/info#getServices
 * Total de serviços: 2000
 */

export const SERVICE_NAMES: Record<string, string> = {
  "aa": "Probo",
  "aaa": "Nubank",
  "aag": "Pockit",
  "aap": "Tiptapp",
  "aaq": "Netease",
  "aar": "Bearwww",
  "aas": "XXGame",
  "aat": "TamTam",
  "aau": "RockeTreach",
  "aav": "Alchemy",
  "aaw": "Aya Bank",
  "aax": "Boyaa",
  "aay": "JioMart",
  "aaz": "Ozan",
  "aba": "Rappi",
  "abb": "Coca-Cola",
  "abc": "Taptap Send",
  "abd": "BeBoo",
  "abe": "Foodora",
  "abf": "Parimatch",
  "abg": "PagBank",
  "abh": "UOL Host",
  "abi": "BytePlus",
  "abj": "Serasa",
  "abk": "GMX",
  "abl": "Gpnbonus",
  "abm": "Утконос",
  "abn": "Bybit",
  "abo": "WEBDE",
  "abp": "D5BET",
  "abq": "Upwork",
  "abr": "Privy",
  "abs": "Playerzpot",
  "abt": "ArenaPlus",
  "abu": "BPJSTK",
  "abv": "PlayZone",
  "abw": "SOKOLOV",
  "abx": "Kaching",
  "aby": "ITMS",
  "abz": "Дарить Легко",
  "ac": "DoorDash",
  "aca": "Sunlight",
  "acb": "Spark Driver",
  "acc": "LuckyLand Slots",
  "acd": "Cloud.ru",
  "ace": "Tata Neu",
  "acf": "Winter Loan",
  "acg": "KoronaPay",
  "ach": "Плайт",
  "aci": "Colombian Cupid",
  "acj": "TeriMeriChoice",
  "ack": "RegainRX",
  "acl": "Swissmoney",
  "acm": "Razer",
  "acn": "Gringo",
  "aco": "AR Lens",
  "acp": "BonusLink",
  "acq": "Astha Tea",
  "acr": "QwikCilver",
  "acs": "Tata CLiQ Palette",
  "act": "Maxis",
  "acu": "CityMall",
  "acv": "A23",
  "acw": "YouDo",
  "acx": "VCollective",
  "acy": "Airtime",
  "acz": "Claude",
  "ad": "Iti",
  "ada": "TRUTH SOCIAL",
  "adb": "PoshVine",
  "adc": "PlayOJO",
  "ade": "Magicpin",
  "adf": "Punjab Timber Traders",
  "adg": "Yono777",
  "adh": "Frizza",
  "adi": "Zepto",
  "adj": "RummyCircle",
  "adk": "Khatabook",
  "adl": "EarnEasy",
  "adm": "FitCredit",
  "adn": "Janganana",
  "ado": "Jasper Home Fashions",
  "adp": "Cabify",
  "adq": "Uzum",
  "adr": "Boosty",
  "ads": "GoChat",
  "adt": "Willhaben",
  "adu": "Seznam",
  "adv": "Cian",
  "adw": "Профи",
  "adx": "FirstCry",
  "ady": "ТОКИО-CITY",
  "adz": "Шоколадница",
  "ae": "MyGLO",
  "aea": "HungryPanda",
  "aeb": "Shine Brand Seeds",
  "aec": "AaHIRA Fashion",
  "aed": "Booking.com",
  "aee": "Amway",
  "aef": "Long Drive Cars",
  "aeg": "Flowwow",
  "aeh": "Аптека Апрель",
  "aei": "Sharyat",
  "aej": "Autoru",
  "aek": "EnerGO",
  "ael": "Cloud Manager",
  "aem": "AstraPay",
  "aen": "Madslots",
  "aeo": "Allofresh",
  "aep": "Slickcall",
  "aeq": "Godrej",
  "aer": "PlayerAuctions",
  "aes": "Золотое Яблоко",
  "aet": "Greywoods",
  "aeu": "TheFork",
  "aev": "Inshallah",
  "aew": "Flip",
  "aex": "Neon",
  "aey": "Next",
  "aez": "Shein",
  "af": "TradeX",
  "afa": "CDEK",
  "afb": "Nebu",
  "afc": "Bunda",
  "afd": "Astra Otoshop",
  "afe": "GovBr",
  "aff": "C6 Bank",
  "afg": "Luck",
  "afh": "MPokket",
  "afi": "Ame Digital",
  "afj": "Laybuy",
  "afk": "Chevron",
  "afl": "Vsesmart",
  "afm": "Myboost",
  "afn": "Roomster",
  "afo": "KION",
  "afp": "VFS GLOBAL",
  "afq": "MagaLu",
  "afr": "Ultragaz",
  "afs": "Privalia",
  "aft": "Neocrypto",
  "afu": "ВсеИнструменты",
  "afv": "PlayCKC",
  "afw": "Packeta",
  "afx": "Gamesofa",
  "afy": "Tuul",
  "afz": "Klarna",
  "aga": "Publi24",
  "agb": "Smiles",
  "agc": "VIMpay",
  "agd": "Grailed",
  "age": "Yetz Promo",
  "agf": "Meitu",
  "agg": "OneForma",
  "agh": "Getnet",
  "agi": "Njuškalo",
  "agj": "Marktplaats",
  "agk": "Ipsos iSay",
  "agl": "Betano",
  "agm": "CMB",
  "agn": "Велобайк",
  "ago": "Servify",
  "agp": "Hdfcbank",
  "agq": "Bajaj Finserv",
  "agr": "Driffle",
  "ags": "Abbott",
  "agt": "Uralairlines",
  "agu": "Marlboro",
  "agv": "DoneDeal",
  "agw": "Adverts",
  "agx": "MeiQFashion",
  "agy": "Pixels",
  "agz": "Jiva Petani",
  "ah": "EscapeFromTarkov",
  "aha": "Angel One",
  "ahb": "Ubisoft",
  "ahc": "START",
  "ahd": "Midnite",
  "ahf": "GAIL`s Bakery",
  "ahg": "Digivarsity Lurningo",
  "ahh": "Cumbuca",
  "ahi": "Daki",
  "ahj": "Strato",
  "ahk": "БлинБери",
  "ahl": "Maxim",
  "ahm": "Eureka",
  "ahn": "Рив Гош",
  "aho": "Upland",
  "ahp": "Handyticket",
  "ahq": "Bitget",
  "ahr": "This Fate",
  "ahs": "1and1",
  "aht": "MockGuru",
  "ahv": "Curve",
  "ahw": "Zasilkovna",
  "ahx": "Bitrue",
  "ahy": "Fliff",
  "ahz": "Кузбасс Онлайн",
  "ai": "CELEBe",
  "aic": "Whoscall",
  "aid": "Kwiff",
  "aie": "Фотострана",
  "aif": "Royal Canin",
  "aig": "Five Surveys",
  "aih": "Fups",
  "aii": "Hinge Dating",
  "aij": "NEQUI",
  "aik": "ZUS Coffee",
  "ail": "Смотрёшка",
  "aim": "Firebase",
  "ain": "SpaceWeb",
  "aio": "Prakerja",
  "aip": "AfreecaTV",
  "aiq": "Prime Opinion",
  "air": "Cleartrip",
  "ais": "DiDiFood",
  "ait": "FeetFinder",
  "aiu": "GetNinjas",
  "aiv": "Remitly",
  "aiw": "Roblox",
  "aix": "Move It",
  "aiy": "Nloto",
  "aiz": "Brevo",
  "aj": "OneAset",
  "aja": "G2A",
  "ajb": "Бери заряд",
  "ajc": "Почта России",
  "ajd": "Bankera",
  "aje": "CupidMedia",
  "ajf": "Bananatok",
  "ajg": "Zaymigo",
  "ajh": "WAUG",
  "aji": "МИГРАНТ СЕРВИС",
  "ajj": "Rebtel",
  "ajk": "Venteny",
  "ajl": "Av100pro",
  "ajm": "Gener8",
  "ajn": "Gopuff",
  "ajo": "CoffeeTea",
  "ajp": "AsiaMiles",
  "ajq": "MyValue",
  "ajr": "Boku",
  "ajs": "GetPlus",
  "ajt": "Город",
  "aju": "Daya Auto",
  "ajv": "ShareParty",
  "ajw": "INDOBA",
  "ajx": "Kemnaker RI",
  "ajy": "All Access",
  "ajz": "MotionPay",
  "ak": "Douyu",
  "aka": "LinkAja",
  "akb": "Gurmanika",
  "akc": "Paybis",
  "akd": "Feels",
  "ake": "DIKIDI",
  "akf": "Ollis",
  "akg": "Book My Play",
  "akh": "Prenagen Club",
  "aki": "Tiketcom",
  "akj": "Easycash",
  "akk": "Dagangan",
  "akl": "DOKU",
  "akm": "LOTTE Mart",
  "akn": "Chakra Rewards",
  "ako": "Ryde",
  "akp": "Her",
  "akq": "Blank Street",
  "akr": "Voi",
  "aks": "Hanya",
  "akt": "Xworldwallet",
  "akw": "WINDS",
  "akx": "Sony LIV",
  "aky": "GOMOFY",
  "akz": "Panvel",
  "ala": "GetResponse",
  "alb": "Guiche Web",
  "alc": "Facily",
  "ald": "Nice88",
  "ale": "Lydia",
  "alf": "WEBULL",
  "alg": "Ankama",
  "alh": "Lion Parcel",
  "ali": "StockyDodo",
  "alj": "Spotify",
  "alk": "HUGESoft",
  "alm": "Muzz",
  "aln": "Remotasks",
  "alo": "Profee",
  "alp": "Mera Gaon",
  "alq": "Etsy",
  "alr": "Vson",
  "als": "Greggs",
  "alt": "Segari",
  "alu": "BC Game",
  "alv": "TIER",
  "alw": "Vida",
  "alx": "NutriClub",
  "aly": "Bebeclub",
  "alz": "CasinoAndFriends",
  "am": "Amazon",
  "ama": "WooPlus",
  "amb": "Vercel",
  "amc": "Fortune Slots",
  "amd": "Smart",
  "ame": "Discover Hong Kong",
  "amf": "Acko",
  "amg": "SBI Card",
  "amh": "MitID",
  "ami": "TEAMORU",
  "amj": "M panels",
  "amk": "GORDAN",
  "aml": "Xbox",
  "amm": "Punjab citizen",
  "amn": "Constitutioner",
  "amo": "CoinFantasy",
  "amp": "VerifyKit",
  "amq": "FRESHOOS",
  "amr": "Univest",
  "ams": "GlowRoad",
  "amt": "Moneyview",
  "amu": "Glassbox",
  "amv": "MeSeems",
  "amw": "Tise",
  "amx": "TANK",
  "amy": "Отзовик",
  "amz": "ImmoScout24",
  "an": "Adidas",
  "ana": "Sicredi",
  "anb": "Abastece-aí",
  "anc": "VARUS",
  "ane": "Supercell",
  "anf": "ZoomInfo",
  "ang": "TOMORO COFFEE",
  "anh": "Cadbury",
  "ani": "Talabat",
  "anj": "Gemini",
  "ank": "Garena",
  "anl": "AttaPoll",
  "anm": "CaltexGO",
  "ann": "Bradesco",
  "ano": "Shopify",
  "anp": "Blackcatcard",
  "anq": "Hitnspin",
  "ant": "Cashew",
  "anu": "Edurators",
  "anv": "Shield",
  "anw": "Premmia",
  "anx": "InfinitePay",
  "any": "FastEarn",
  "anz": "TopGun",
  "ao": "UU163",
  "aoa": "Hicard",
  "aob": "Anthropic",
  "aoe": "Sendwave",
  "aof": "Guzman y Gomez",
  "aog": "Naukri",
  "aoh": "ЮMoney",
  "aoi": "Cryptonow",
  "aoj": "Simply",
  "aok": "NETELLER",
  "aol": "Paysera",
  "aom": "Monzo",
  "aon": "Binance",
  "aoo": "Pegasus Airlines",
  "aoq": "JB Hi-Fi",
  "aor": "OKX",
  "aos": "Loloo",
  "aot": "Diversity",
  "aou": "IT Business Group",
  "aov": "Zanimaika",
  "aox": "Aukro",
  "aoy": "PLN Mobile",
  "apa": "Exness",
  "apb": "EToro",
  "apc": "IGameBUY",
  "apd": "2dehands",
  "ape": "Toutiao",
  "apf": "Carrefour",
  "apg": "Damai",
  "aph": "Openbudget",
  "api": "KKTIX",
  "apj": "Tinkoff VoiceKit",
  "apk": "Liberty",
  "apl": "Sideline",
  "apm": "Index",
  "apo": "Netmarble",
  "app": "ClassPass",
  "appendix": "2. List of services",
  "apq": "WePoker",
  "apr": "Capital One",
  "aps": "Skelbiu",
  "apt": "Airwallex",
  "apu": "LIC Games",
  "apw": "Bankiros",
  "apy": "Винлаб",
  "apz": "Wynk",
  "aq": "Glovo",
  "aqa": "Satori",
  "aqb": "Pinoy Peso",
  "aqc": "Omne by FWD",
  "aqd": "Pesohere",
  "aqe": "PeraMoo",
  "aqf": "Coze",
  "aqg": "Publix",
  "aqh": "Rayobyte",
  "aqi": "Cairon Fashion",
  "aqj": "BigBasket",
  "aqk": "Richkart",
  "aql": "Xigua Video 西瓜视频",
  "aqm": "Tala",
  "aqn": "CashMyPic",
  "aqo": "XREWARD",
  "aqp": "Golden Plus GP",
  "aqq": "MPSTATS",
  "aqr": "SportEfir",
  "aqs": "BetOnRed",
  "aqt": "Skrill",
  "aqu": "KBX",
  "aqv": "Doorverse",
  "aqw": "Edvantum",
  "aqx": "XL-PEarl",
  "aqy": "SAPO",
  "aqz": "BlazeTech",
  "ar": "Wondermart",
  "ara": "Shareful",
  "arb": "Las Vegas Casino",
  "arc": "CHECK24",
  "ard": "Maya",
  "are": "Seated",
  "arf": "Enjoei",
  "arg": "Gappx",
  "arh": "Super Ace",
  "ari": "Ring4",
  "arj": "E2zSTORE",
  "ark": "SageMaker Studio Lab",
  "arl": "Mainvest",
  "arm": "Cathay Pacific",
  "arn": "GFK",
  "aro": "GGPoker",
  "arp": "Continente",
  "arq": "Adapundi",
  "arr": "Линии Любви",
  "ars": "Bingo Plus",
  "aru": "UNNI 강남언니",
  "arv": "DARKSIDE",
  "arw": "ASA",
  "arx": "Zinia",
  "ary": "Presto",
  "arz": "Cineplex",
  "asa": "Habby",
  "asb": "YUEWEN 阅文集团",
  "asd": "Hongguo 红果短剧",
  "ase": "Collection Pot",
  "asf": "TextFree",
  "asg": "Asetku",
  "ash": "Pinjam Yuk",
  "asi": "OMODA",
  "ask": "СВОЁ",
  "asl": "Familhao",
  "asm": "PH777",
  "asn": "Boletomovil",
  "aso": "RL Solution",
  "asp": "PhonePe",
  "asq": "Warpcast",
  "asr": "LA VOZ DEL PACIENTE",
  "ass": "CICIL",
  "ast": "THXapp",
  "asu": "Replit",
  "asv": "Bilderlings",
  "asw": "ACSON",
  "asx": "KIMGRES",
  "asy": "Fore Coffee",
  "asz": "Fonial",
  "at": "Perfluence",
  "ata": "Authy",
  "atb": "Movider",
  "atc": "Lemo",
  "atd": "BUKA",
  "ate": "GETAWARD",
  "atf": "Asharfi Design",
  "atg": "Mandi Bhav",
  "ath": "Samarth Diamond App",
  "ati": "Kullut",
  "atj": "Klin",
  "atk": "ARCH",
  "atl": "Watsons MY",
  "atm": "Yotta",
  "atn": "Fawry",
  "ato": "Podrygka",
  "atp": "Vonage",
  "atq": "PQHosting",
  "atr": "RIDE",
  "ats": "Fave",
  "att": "BCD travel",
  "atu": "Sber/Cooper",
  "atv": "快手 Kuaishou",
  "atw": "DeepSeek",
  "atx": "Winee3",
  "atz": "Air India",
  "aua": "同程旅行 Tongcheng Travel",
  "aub": "Smitten",
  "auc": "TotalPass",
  "aud": "BkSMS",
  "aue": "TicketOne",
  "auf": "PREMIER",
  "aug": "Магнит Маркет",
  "auh": "KeeTa 美团",
  "aui": "IDOLCHAMP",
  "auj": "High 5 Casino",
  "auk": "STB Union",
  "aul": "Alignable",
  "aum": "Chipper Cash",
  "aun": "Morinaga",
  "auo": "Mycashbacks",
  "aup": "Botim",
  "auq": "WeLive",
  "aur": "The Concert",
  "aus": "PalawanPay",
  "aut": "Миллионъ",
  "auu": "Четыре Лапы",
  "auv": "ФК «Спартак»",
  "auw": "3Fun",
  "aux": "Lightning AI",
  "auy": "LivU",
  "auz": "Outlier",
  "av": "Avito",
  "ava": "E-CNY",
  "avb": "Tealive",
  "avd": "NCA888",
  "ave": "BizneX",
  "avf": "ONESIAM",
  "avg": "Hooked Protocol",
  "avh": "XM",
  "avi": "Oye Turtle",
  "avj": "SumUp",
  "avk": "Quoka",
  "avl": "BRImo BRI",
  "avm": "Instacart",
  "avn": "G42",
  "avo": "Twikey",
  "avp": "Ripio",
  "avq": "Wego",
  "avr": "OJ",
  "avs": "Wooppay",
  "avt": "HuntTheMouse",
  "avu": "Karos",
  "avv": "ShopFarEast",
  "avw": "Great Rewards",
  "avx": "Zazzle",
  "avz": "Getsbet",
  "aw": "Taikang",
  "awa": "NHN Cloud",
  "awb": "FlixBus",
  "awc": "Nestle Baby",
  "awe": "MyGift",
  "awf": "Rothmans",
  "awg": "Natura Avon",
  "awh": "NGCASH",
  "awi": "ALY",
  "awj": "HyperJar",
  "awk": "Bereke Bank",
  "awl": "KitaBeli",
  "awm": "Grosenia",
  "awn": "DialMyCalls",
  "awo": "GreatDay SunFish",
  "awp": "Clapper",
  "awq": "Atlas Earth",
  "awr": "KCEX",
  "aws": "7-Eleven",
  "awt": "BlockDag",
  "awu": "MosGram",
  "awv": "Wallapop",
  "aww": "Pecunpay",
  "awx": "BusyFly",
  "awy": "Kia",
  "awz": "PlayTime",
  "ax": "CrefisaMais",
  "axa": "Social Nature",
  "axb": "TrueID",
  "axc": "One World Connect",
  "axd": "STK",
  "axe": "MocaMoca",
  "axf": "Hinance",
  "axg": "Twin",
  "axh": "TAOVIP",
  "axi": "ProductLab",
  "axj": "FIFGROUP MOBILE CUSTOMER",
  "axk": "BandinginAja",
  "axl": "Viralmu",
  "axm": "Não Me Perturbe",
  "axn": "FastMoss",
  "axo": "Fanatics Live",
  "axp": "ChargePoint",
  "axq": "Eventbrite",
  "axr": "Match",
  "axs": "AIS PLAY",
  "axt": "GNJOY",
  "axu": "Sipay",
  "axv": "AIA 友邦保險",
  "axw": "Allē",
  "axx": "Shopback",
  "axy": "Alcon",
  "axz": "WarPin",
  "ay": "Ruten",
  "aya": "Gopay",
  "ayb": "AsianDating",
  "ayc": "HungerStation",
  "ayd": "NocNoc",
  "aye": "SmartSari",
  "ayf": "ITV",
  "ayg": "Leroy Merlin",
  "ayh": "GB Wallet",
  "ayi": "Klook",
  "ayj": "Realme",
  "ayk": "Radquest",
  "ayl": "WPK",
  "aym": "Langit Musik",
  "ayn": "Lime",
  "ayo": "360Kredi",
  "ayp": "VYBE by BPI",
  "ayq": "Победа 63",
  "ayr": "Superbet",
  "ays": "ICW Connect",
  "ayt": "Roqqu",
  "ayu": "Think Academy",
  "ayv": "MyTVSUPER",
  "ayw": "E4B",
  "ayx": "C24 Bank",
  "ayy": "Rabbit",
  "ayz": "Kimi",
  "az": "CityBase",
  "aza": "Hypernet of Things",
  "azb": "AlphaI",
  "azc": "CoreAsia",
  "azd": "Вплюсе",
  "aze": "Beehiiv",
  "azf": "Welocalize",
  "azg": "LODA",
  "azi": "TheL",
  "azj": "MariPinjam",
  "azk": "KreditMart",
  "azl": "MotoRan",
  "azm": "Ticket Plus",
  "azn": "UFC",
  "azo": "Jegotrip",
  "azp": "Senthil Murugan Jewellers",
  "azq": "CRED",
  "azr": "PayFix",
  "azs": "Магнолия",
  "azt": "Fidelity Investments",
  "azu": "Ninjaz",
  "azv": "Tangga",
  "azw": "Espresso House",
  "azx": "ToYou",
  "azy": "Casa Pariurilor",
  "azz": "Crystalbet",
  "ba": "Expressmoney",
  "baa": "Wirex",
  "bab": "Opera Mini",
  "bac": "IndiaMart",
  "bad": "ALL IT",
  "bae": "Topchop",
  "baf": "Urbanic",
  "bag": "Taurus",
  "bah": "Afriex",
  "bai": "SNKRDUNK",
  "baj": "Bipa",
  "bak": "LiveCode",
  "bal": "Moka",
  "bam": "The Haat",
  "ban": "BLINK by BonusLink",
  "bao": "SUGO",
  "bap": "HAPPYBET",
  "baq": "Redbubble",
  "bar": "BJP",
  "bas": "Stoiximan",
  "bat": "Muathegame",
  "bau": "FieldStar",
  "bav": "LeoList",
  "baw": "Leadgid",
  "bax": "Теремок",
  "bay": "Genome",
  "bb": "LazyPay",
  "bba": "SwitchUp",
  "bbb": "Dscout",
  "bbc": "SparkBlend",
  "bbd": "DBS Bank",
  "bbe": "Branch",
  "bbf": "Neosurf",
  "bbg": "Square",
  "bbh": "Qbet",
  "bbi": "Aiqfome",
  "bbj": "OnePay",
  "bbk": "FilipinoCupid",
  "bbl": "Autodesk",
  "bbm": "TrueMoney",
  "bbn": "Norstat",
  "bbo": "Аскона",
  "bbp": "LineBet",
  "bbq": "Chime",
  "bbr": "WalletHub",
  "bbs": "Ecoplatform",
  "bbt": "Blink",
  "bbu": "InternationalCupid",
  "bbv": "Биннофарм Групп",
  "bbw": "Foxy",
  "bbx": "ServeXplus",
  "bby": "TATA 1mg",
  "bbz": "LionsgatePlay",
  "bc": "GCash",
  "bca": "Shop101",
  "bcb": "Codapay",
  "bcc": "JULO",
  "bcd": "Belanjayuk",
  "bce": "BUSQO",
  "bcf": "Hoff",
  "bcg": "2ГИС",
  "bch": "CyberLotus",
  "bci": "Pesobox",
  "bcj": "Escort Advisor",
  "bck": "Onion Academy 洋葱学园",
  "bcl": "YONOPay",
  "bcm": "KANOE",
  "bcn": "Tipsport Gamechanger",
  "bco": "Ситилинк",
  "bcp": "DLS",
  "bcq": "Mantan",
  "bcr": "ESX",
  "bcs": "Ocard",
  "bct": "Neoteq",
  "bcu": "BT One",
  "bcv": "Britannia",
  "bcw": "Online Check Writer",
  "bcx": "Bantusaku",
  "bcy": "Finplus",
  "bcz": "UATAS",
  "bda": "The Simple Peso",
  "bdb": "ОБИ",
  "bdc": "Veo",
  "bdd": "BetMen",
  "bde": "Шаверно",
  "bdf": "Xegr",
  "bdg": "HUD",
  "bdh": "Singledk",
  "bdi": "Копилка",
  "bdj": "Findo",
  "bdk": "Veera",
  "bdl": "Frankly",
  "bdm": "Octobank",
  "bdn": "Teman Prima",
  "bdo": "AdaModal",
  "bdp": "Kredito",
  "bdq": "Paydy",
  "bds": "رسال resal",
  "bdt": "HOT51",
  "bdu": "星城Online",
  "bdv": "Mudah",
  "bdw": "Valora",
  "bdx": "Benjamin",
  "bdy": "Justdial",
  "bdz": "Watcho",
  "be": "СберМегаМаркет",
  "bea": "Binmo",
  "beb": "Rotiboy",
  "bec": "Migo",
  "bed": "NetBet",
  "bee": "SKO",
  "bef": "Parker Cards",
  "beg": "Global Cash",
  "beh": "LUUP",
  "bei": "Measat",
  "bej": "KERETAKU",
  "bek": "Chubb",
  "bel": "ShineIn",
  "bem": "Shafa",
  "ben": "MPower",
  "beo": "BigPay",
  "bep": "Турбо",
  "beq": "Литрес",
  "ber": "Gumtree",
  "bes": "RusNovo",
  "beu": "BRAX",
  "bev": "ITN",
  "bew": "Mariyas Naturals",
  "bex": "Whatnot",
  "bey": "La3eb",
  "bez": "Boom Market",
  "bf": "Keybase",
  "bfa": "Webmotors",
  "bfb": "Mudrex",
  "bfc": "Tomei",
  "bfd": "Kalodata",
  "bfe": "MuchBetter",
  "bff": "Kawan Food",
  "bfg": "EMAG",
  "bfh": "Finom",
  "bfi": "Wcode",
  "bfj": "Good Morning Global",
  "bfk": "Pharmaniaga",
  "bfl": "Beebop Circus",
  "bfm": "Simplysiti",
  "bfn": "Tualang Honey",
  "bfo": "MSport",
  "bfp": "GrapeData",
  "bfq": "MyPAT",
  "bfr": "Dott",
  "bfs": "BUYBUYGO",
  "bft": "RUS-zaimru",
  "bfu": "Boostra",
  "bfv": "Chocofamily",
  "bfw": "Finya",
  "bfx": "ANTHE AAKASH",
  "bfy": "The Dots",
  "bfz": "Snapmint",
  "bg": "MIXMART",
  "bga": "LPTracker",
  "bgb": "EZMatch",
  "bgc": "AJIO",
  "bgd": "GS World",
  "bge": "T2P",
  "bgf": "Rapido",
  "bgg": "Link",
  "bgh": "SayHi Chat",
  "bgi": "SuperLive",
  "bgj": "MoonPay",
  "bgk": "AXS",
  "bgl": "DeLorean Labs",
  "bgm": "BlockPicks",
  "bgn": "Veeka",
  "bgo": "MTrading",
  "bgp": "Accuindex",
  "bgq": "Zalabin",
  "bgr": "Superbank",
  "bgs": "Pintu",
  "bgt": "Alfamidi",
  "bgu": "EffLink",
  "bgv": "Clearpay",
  "bgw": "Freedom24",
  "bgx": "Paxel",
  "bgy": "Astro",
  "bgz": "Deloitte",
  "bh": "Uteka",
  "bha": "Kopi Kenangan",
  "bhb": "Wuling",
  "bhc": "Creaplay",
  "bhd": "IPiu",
  "bhe": "Jago",
  "bhf": "InPost",
  "bhg": "Telz",
  "bhh": "Appen",
  "bhi": "Chase",
  "bhj": "Jòfogàs",
  "bhk": "Qumpara",
  "bhl": "Ati su",
  "bhm": "BETL",
  "bhn": "TopCashback",
  "bho": "Знание",
  "bhp": "PPC",
  "bhq": "Solitaire Cash",
  "bhr": "Dil Mil",
  "bhs": "Bingo Cash",
  "bht": "Luno",
  "bhu": "TMTW",
  "bhv": "Savbra",
  "bhw": "Столички",
  "bhx": "Пава Пава",
  "bhy": "HighLevel",
  "bhz": "Eurobet",
  "bi": "勇仕网络Ys4fun",
  "bia": "COYO",
  "bib": "MyBCA",
  "bic": "Marktde",
  "bid": "Hablax",
  "bie": "Shinjiru",
  "bif": "OPAP",
  "big": "Копійочка",
  "bih": "Indosaku",
  "bii": "MEXC",
  "bij": "Prodege",
  "bik": "Hanwha Life",
  "bil": "SafeW",
  "bim": "Синема Парк",
  "bin": "Baggins Coffee",
  "bio": "PeryaGame",
  "bip": "Горздрав",
  "biq": "Xpress Super App",
  "bir": "FloatMe",
  "bis": "MPaisa",
  "bit": "Домклик",
  "biu": "Siesta",
  "biv": "Sonline",
  "biw": "Kome",
  "bix": "Hotel101",
  "biy": "TaDa",
  "biz": "BeCharge",
  "bj": "Вита экспресс",
  "bja": "QuackQuack Dating App",
  "bjb": "PaySprint",
  "bjc": "Daraz",
  "bjd": "Iconcept",
  "bje": "Meest",
  "bjf": "Dubizzle",
  "bjg": "GlobalNet",
  "bjh": "NGN",
  "bji": "Perfect World 完美世界",
  "bjj": "Osem",
  "bjk": "ElectroPay",
  "bjl": "Digio",
  "bjm": "Cheddar",
  "bjn": "SaltyCustoms",
  "bjo": "Smooshie Juice",
  "bjp": "Ria",
  "bjq": "Surveyon",
  "bjr": "Pony",
  "bjs": "Автор24",
  "bjt": "OCBC",
  "bju": "Odix Pay",
  "bjv": "LotoClub",
  "bjw": "Paripesa",
  "bjx": "Monster Energy",
  "bjy": "Shaadi",
  "bjz": "Jeevansathi",
  "bk": "G2G",
  "bka": "Pipwave",
  "bkb": "CMK Club",
  "bkc": "CoinTR",
  "bkd": "Sahibinden",
  "bke": "FOOTDISTRICT",
  "bkf": "MyXL",
  "bkg": "Vprok",
  "bkh": "Т-Мобайл",
  "bki": "MyACUVUE",
  "bkj": "Давай делить",
  "bkk": "Poparide",
  "bkl": "Uancomm",
  "bkm": "MoneyHelp",
  "bkn": "Betlive",
  "bko": "Vision Plus",
  "bkp": "MakeMyTrip",
  "bkq": "FT Cabs",
  "bkr": "Storm EduGo",
  "bks": "Heetch",
  "bkt": "IngramSpark",
  "bku": "NL International",
  "bkv": "Zen",
  "bkw": "Bilkraft",
  "bkx": "Mi Gente",
  "bky": "Tesco",
  "bkz": "Rewardy",
  "bl": "BIGO LIVE",
  "bla": "FDJ ParionsSport",
  "blb": "Foundit",
  "blc": "Дикси",
  "bld": "Сибирское Здоровье",
  "ble": "Nexon",
  "blf": "Malabar",
  "blg": "KOPI SUSU",
  "blh": "Winner",
  "bli": "Scalapay",
  "blj": "Brace",
  "blk": "HDI",
  "bll": "Black GSM",
  "blm": "Epic Games",
  "bln": "Pawshake",
  "blo": "SiliconFlow 硅基流动",
  "blp": "MEEFF",
  "blq": "Ari10",
  "blr": "DocuSign",
  "bls": "WeTV",
  "blt": "INDOPAKET",
  "blu": "SurveyRewardz",
  "blv": "Pepsi",
  "blw": "BP",
  "blx": "2ememain",
  "bly": "COSMOTE",
  "blz": "MiniPay",
  "bm": "MarketGuru",
  "bma": "Acerta e Recicla",
  "bmb": "Газпром ID",
  "bmc": "Хорошие новости",
  "bmd": "VooV Meeting",
  "bme": "MyIM3",
  "bmf": "K-RITEL",
  "bmg": "Emoney",
  "bmh": "Welink",
  "bmi": "Sisal",
  "bmj": "Betflag",
  "bmk": "Автополе",
  "bml": "Wavy",
  "bmm": "Hey Cash",
  "bmn": "Motina",
  "bmo": "Kviku",
  "bmp": "Ourbit",
  "bmq": "Royale",
  "bmr": "NCISM",
  "bms": "Playpark",
  "bmt": "Worldgas",
  "bmu": "Newsoft",
  "bmv": "Emma AXA Mandiri",
  "bmw": "JChicken",
  "bmx": "Canal RCN",
  "bmy": "ХолодильникРу",
  "bmz": "Rumble",
  "bn": "Alfagift",
  "bna": "Practo",
  "bnb": "Hopper",
  "bnc": "Infomaniak",
  "bnd": "КуулКлевер",
  "bne": "HM",
  "bnf": "ContiCazino",
  "bng": "Jush",
  "bnh": "Philip Morris",
  "bni": "Pets4Homes",
  "bnj": "Notarielle",
  "bnk": "CAAI",
  "bnl": "Reddit",
  "bnm": "TangoMe",
  "bnn": "KOHO",
  "bno": "Welo Data",
  "bnp": "Airba Fresh",
  "bnq": "Fortuna",
  "bns": "PAC Cash",
  "bnt": "Treasury",
  "bnu": "Qpon",
  "bnv": "IN1",
  "bnw": "Medium",
  "bnx": "Allianz",
  "bny": "Suno",
  "bnz": "Seven Bet",
  "bo": "Wise",
  "boa": "Excellent",
  "bob": "Shell GO",
  "boc": "51exch",
  "bod": "Genspark",
  "boe": "HP Gas Vitran",
  "bof": "Davaka",
  "bog": "France Mobilities",
  "boh": "Yophone",
  "boj": "NIKO",
  "bok": "Riobet",
  "bol": "My TELUS",
  "bom": "Solcredito",
  "bon": "RetailMeNot",
  "boo": "Casino Plus",
  "bop": "Везёт",
  "boq": "Lider",
  "bor": "Bitpanda",
  "bos": "Casino Portugal",
  "bot": "EGS",
  "bou": "汇旺 Huione Pay",
  "bov": "Naiin",
  "bow": "Affirm",
  "box": "Thumbtack",
  "boy": "Ixigo",
  "boz": "Doctu",
  "bp": "GoFundMe",
  "bpa": "OP Braga",
  "bpb": "Outbox",
  "bpc": "LOVOO",
  "bpe": "Сільпо",
  "bpf": "Fix Price",
  "bpg": "НаПоправку",
  "bph": "Bibi",
  "bpi": "Askable",
  "bpj": "PMSURYAGHAR",
  "bpk": "Huggies",
  "bpl": "Flaming",
  "bpm": "Porter",
  "bpn": "Namirial",
  "bpo": "Clerk",
  "bpp": "Bliq",
  "bpq": "MChat",
  "bpr": "Waha",
  "bps": "Indiluck",
  "bpt": "SerpApi",
  "bpu": "TCONE",
  "bpv": "Портал",
  "bpw": "HONOR",
  "bpx": "Haiilo",
  "bpy": "Quicko",
  "bpz": "Just Eat",
  "bq": "Adani",
  "bqa": "AirAsia MOVE",
  "bqb": "Weex",
  "bqc": "Wigl",
  "bqd": "EasyPark",
  "bqe": "Lottomatica",
  "bqf": "NUUM",
  "bqg": "INFORMPSKOV",
  "bqh": "PEDIR GAS",
  "bqi": "Datanyze",
  "bqj": "QQPK",
  "bqk": "Lex",
  "bql": "Бетховен",
  "bqm": "Beebs",
  "bqn": "Upward",
  "bqo": "Caffe Nero",
  "bqp": "Zara",
  "bqq": "Intersport",
  "bqr": "ASAAS",
  "bqs": "CGV",
  "bqt": "PENTA",
  "bqu": "KasPro",
  "bqv": "Yuzu",
  "bqw": "KPN Fresh",
  "bqx": "Club Q8",
  "bqy": "SNAI",
  "bqz": "Credit Karma",
  "br": "Вкусно и Точка",
  "bra": "Touch n Go TNG",
  "brb": "Hohoro",
  "brc": "Casa it",
  "brd": "Budgett ru",
  "bre": "Лемана ПРО",
  "brf": "Dolap",
  "brg": "Letgo",
  "brh": "Efsane",
  "bri": "Gardrops",
  "brj": "Planet fans",
  "brk": "Indeed",
  "brl": "Paperspace",
  "brm": "Locanto",
  "brn": "Tune AI",
  "bro": "YouGov Shopper",
  "brp": "Аптечество",
  "brq": "Фармленд",
  "brr": "LemFi",
  "brs": "MioDottore",
  "brt": "Netwin",
  "bru": "MyPOS",
  "brv": "999 md",
  "brw": "Sendy",
  "brx": "CoinW",
  "bry": "Mobile DE",
  "brz": "FuelCycle",
  "bs": "TradeUP",
  "bsa": "Will",
  "bsb": "Fasset",
  "bsc": "Shielded",
  "bsd": "Codeium",
  "bse": "ЛигаМФО",
  "bsf": "Rupiah Cepat",
  "bsg": "SticksnSushi",
  "bsh": "YELL VOTE",
  "bsi": "SMSPILOT",
  "bsj": "Pagaleve",
  "bsk": "Web3Auth",
  "bsl": "Oskelly",
  "bsm": "Ahlan",
  "bsn": "RelicDAO",
  "bso": "PayWell",
  "bsp": "StarterApp",
  "bsq": "KNECTT",
  "bsr": "Janapriya",
  "bss": "Trade Republic",
  "bst": "AdmiralBet",
  "bsu": "Dingtone",
  "bsv": "AmarthaFin",
  "bsw": "Milanuncios",
  "bsx": "KulturPass",
  "bsy": "Air Miles",
  "bsz": "Sling Money",
  "bt": "Alfa",
  "bta": "TCLOUD",
  "btb": "SM Malls Online",
  "btd": "Volcengine 火山引擎",
  "bte": "CROCOBET",
  "btf": "Blackbird",
  "btg": "Whoppah",
  "bth": "Caranga",
  "bti": "Sayurbox",
  "btj": "SBL-pharma",
  "btk": "Mais Store",
  "btl": "D4",
  "btm": "ZeeNow",
  "btn": "Itau",
  "bto": "Планета АВТО",
  "btp": "Связь ON",
  "btq": "ЭЛПЛАТ",
  "btr": "Duet",
  "bts": "Trustee Plus",
  "btt": "Copec",
  "btu": "DDX Fitness",
  "btv": "Radiate",
  "btw": "CloudTips",
  "btx": "Amap 高德地图",
  "bty": "QueBueno",
  "btz": "IRWIN",
  "bu": "MonobankIndia",
  "bua": "Mistral AI",
  "bub": "Sparda Bank",
  "buc": "Wargaming",
  "bud": "WeTalk",
  "bue": "映客 inke",
  "buf": "Web8",
  "bug": "2GO",
  "buh": "Jai Foods",
  "bui": "OKbet",
  "buj": "ASVLA",
  "buk": "NABIS",
  "bul": "Openbank",
  "bum": "Wahana Honda",
  "bun": "Fat Llama",
  "buo": "HRBlock",
  "bup": "THX",
  "buq": "로드나인 LORDNINE",
  "bur": "Tayyab",
  "bus": "OKOLO Market",
  "but": "Milliysmm",
  "buu": "STS",
  "buv": "Avosend",
  "buw": "NewPort",
  "bux": "I1DA",
  "buy": "GetBlogger",
  "buz": "Jitume",
  "bv": "Metro",
  "bva": "Bingo101",
  "bvb": "Uphold",
  "bvc": "ELEV8",
  "bvd": "SOCIALMATTE",
  "bve": "VerdeCasino",
  "bvf": "GymPlius",
  "bvg": "Gizbo",
  "bvh": "ParenTeam",
  "bvi": "Salams",
  "bvj": "Санофи",
  "bvk": "Salampay",
  "bvl": "Psysu",
  "bvm": "Тикетон",
  "bvn": "Globo",
  "bvo": "KKP",
  "bvp": "Forte",
  "bvq": "PREMIUM BANDAI",
  "bvr": "SBM Urban",
  "bvs": "Вчасно",
  "bvt": "SoCo",
  "bvu": "SwaRail",
  "bvv": "Ride amigo",
  "bvw": "Rida",
  "bvx": "Lagkagehuset",
  "bvy": "Waje",
  "bvz": "TourCMR",
  "bw": "Signal",
  "bwa": "Hostinger",
  "bwb": "Winmatch365",
  "bwc": "Vision11",
  "bwd": "Fetch",
  "bwe": "Immutable Play",
  "bwf": "MyGo",
  "bwg": "Бристоль",
  "bwh": "EOS RED 靈境殺戮",
  "bwi": "CIMB",
  "bwj": "Bata",
  "bwk": "Sorted Wallet",
  "bwl": "Guthabende",
  "bwm": "YamahaMotor",
  "bwn": "Viendong",
  "bwo": "KabanchikUA",
  "bwp": "ГЛОБУС",
  "bwq": "AmazingTalker",
  "bwr": "Cita",
  "bws": "Citygo",
  "bwt": "Stanleybet",
  "bwu": "SkyBet",
  "bwv": "Manus",
  "bww": "Wert",
  "bwx": "Chagee",
  "bwy": "Монетка",
  "bwz": "Box Coupon",
  "bx": "Dosi",
  "bxa": "Teboil",
  "bxb": "ICard",
  "bxc": "DRIVE2",
  "bxd": "Jackaroo",
  "bxe": "Bitexen",
  "bxf": "Disney Plus",
  "bxg": "BAT",
  "bxh": "Acordo Certo",
  "bxi": "Grupo Madero",
  "bxj": "Quero-Quero PAG",
  "bxk": "UAE PASS",
  "bxl": "Findom",
  "bxm": "Prezzee",
  "bxn": "Intel SAP",
  "bxo": "悠遊卡 EasyCard",
  "bxp": "Tennents",
  "bxq": "OURO",
  "bxr": "AlFursan",
  "bxs": "LikeCard",
  "bxt": "ZEMPOT",
  "bxu": "Chronodrive",
  "bxv": "PAPER",
  "bxx": "Wallester",
  "bxy": "MAX",
  "bxz": "SOOP",
  "bya": "MICO",
  "byb": "WannaPay",
  "byc": "Vantage",
  "byd": "Airtasker",
  "bye": "WhatsApp Business",
  "byf": "SeaBank",
  "byg": "Jeton",
  "byh": "Adobe",
  "byi": "Ambassadoribet",
  "byj": "Sorpa",
  "byk": "Dynata e-Rewards",
  "byl": "Nala",
  "bym": "Yonder",
  "byn": "Orbit Жуй выдыхай",
  "byo": "АВТОМОЁ",
  "byp": "Kaito",
  "byq": "Ikualo",
  "byr": "Место Встречи Планета",
  "byu": "Allpay",
  "byv": "Dutch Bros",
  "byw": "Annoncelight",
  "byx": "Hopp",
  "byy": "Dreamcash",
  "byz": "WikiFX",
  "bz": "Blizzard",
  "bza": "VieON",
  "bzb": "Big Cash",
  "bzc": "KAMI",
  "bzd": "Laylo",
  "bze": "ILOTBET",
  "bzf": "Dabble",
  "bzg": "Toyota",
  "bzh": "Tikkie",
  "bzi": "MoneyBack 易賞錢",
  "bzj": "Talk360",
  "bzk": "Amaze Super App",
  "bzl": "Doctoralia",
  "bzm": "Storewards",
  "bzn": "CA Club",
  "bzo": "SeLoger",
  "bzp": "Farmatodo",
  "bzq": "Maitix 麦座",
  "bzr": "EMOS",
  "bzs": "Finzmo",
  "bzt": "Hapi",
  "bzu": "BTG Pactual",
  "bzv": "TOP",
  "bzw": "Efi",
  "bzx": "BLUE Rewards",
  "bzy": "Chroma Awards",
  "bzz": "Elite Competitions",
  "ca": "SuperS",
  "caa": "Vshow",
  "cab": "DHL",
  "cac": "Vesseo",
  "cad": "BOSS Revolution",
  "cae": "Ploom",
  "caf": "Leon Club",
  "cag": "Cora",
  "cah": "AhoraCrypto",
  "cai": "InKind",
  "caj": "GoMoney",
  "cak": "Bazaraki",
  "cal": "Game Zone",
  "cam": "Eleme 饿了么",
  "can": "BAGI",
  "cao": "BBVA",
  "cap": "Moomoo",
  "caq": "Stone",
  "car": "Sofisa Direto",
  "cas": "Koin",
  "cat": "Conta Simples",
  "cau": "Ero Me",
  "cav": "Adspay",
  "caw": "GinjaBet",
  "cax": "Veezu",
  "cay": "Seamless AI",
  "caz": "Sainsburys",
  "cb": "Bazos",
  "cba": "Enilive",
  "cbb": "KeepCalling",
  "cbc": "BCW",
  "cbd": "Hornet",
  "cbe": "ACU Pay",
  "cbf": "Fivebet",
  "cbg": "XP Investimentos",
  "cbh": "ZUL",
  "cbi": "EBpay",
  "cbj": "DaTalk",
  "cbk": "Fastwork",
  "cbl": "Epharma",
  "cbm": "PUBG",
  "cbn": "TrueCOLOR 本色",
  "cbo": "Dindongmall",
  "cbp": "Justice Online 逆水寒",
  "cbr": "Mail2World",
  "cbs": "Lalafo",
  "cbt": "KashCash",
  "cbu": "ZapStep",
  "cbv": "MyCard",
  "cbw": "FastPari",
  "cbx": "GitLab",
  "cby": "Uhuu",
  "cbz": "Starling",
  "cc": "Quipp",
  "cca": "Cetelem",
  "ccb": "Nintendo",
  "ccc": "Zopa",
  "ccd": "MySabay",
  "cce": "Melbet",
  "ccf": "StepFun",
  "ccg": "Ytowait",
  "cch": "Luxury Escapes",
  "cci": "Spliiit",
  "ccj": "Sonol",
  "cck": "Quoty",
  "ccl": "Cruzeiro",
  "ccm": "Blueticket",
  "ccn": "Mang Sunwork",
  "cco": "Royal Bank of Scotland",
  "ccp": "HPay",
  "ccq": "MyTOWNKL",
  "ccr": "T-POP",
  "ccs": "VMix",
  "cct": "Factory",
  "ccu": "Google Chat",
  "cd": "SpotHit",
  "ce": "Mosru",
  "cf": "Irancell",
  "cg": "Gemgala",
  "ch": "Pocket52",
  "ci": "RedBus",
  "cj": "Dotz",
  "ck": "BeReal",
  "cl": "UWIN",
  "cm": "Prom",
  "cn": "Fiverr",
  "co": "Rediffmail",
  "cp": "Uklon",
  "cq": "Mercado",
  "cr": "TenChat",
  "cs": "AgriDevelop",
  "ct": "КухняНаРайоне",
  "cu": "炙热星河",
  "cv": "WashXpress",
  "cx": "Icrypex",
  "cy": "РСА",
  "cz": "Getmega",
  "da": "MTS CashBack",
  "db": "Ezbuy",
  "dc": "YikYak",
  "dd": "CloudChat",
  "de": "Karusel",
  "df": "Happn",
  "dg": "Mercari",
  "dh": "EBay",
  "di": "Loanflix",
  "dj": "LUKOIL-AZS",
  "dk": "Pairs",
  "dl": "Lazada",
  "dm": "Iwplay",
  "dn": "Paxful",
  "do": "Leboncoin",
  "dp": "ProtonMail",
  "dq": "IceCasino",
  "dr": "OpenAI",
  "ds": "Discord",
  "dt": "Delivery Club",
  "du": "AUBANK",
  "dv": "NoBroker",
  "dw": "Divar",
  "dx": "Powerkredite",
  "dy": "Zomato",
  "dz": "Dominos Pizza",
  "ea": "JamesDelivery",
  "eb": "Voltz",
  "ec": "RummyCulture",
  "ed": "Gamer",
  "ee": "Twilio",
  "ef": "Nextdoor",
  "eg": "ContactSys",
  "eh": "Telegram 2.0",
  "ei": "Taksheel",
  "ej": "MrQ",
  "el": "Bisu",
  "em": "ZéDelivery",
  "en": "Hermes",
  "eo": "Sizeer",
  "ep": "Temu",
  "eq": "Qoo10",
  "es": "IQIYI",
  "et": "Clubhouse",
  "eu": "LiveScore",
  "ev": "Picpay",
  "ew": "Nike",
  "ex": "Linode",
  "ey": "Miloan",
  "ez": "GoerliFaucet",
  "fa": "XadrezFeliz",
  "fb": "Facebook",
  "fc": "PharmEasy",
  "fd": "Mamba",
  "fe": "CliQQ",
  "ff": "AVON",
  "fg": "IndianOil",
  "fh": "Lalamove",
  "fi": "Dundle",
  "fj": "Potato Chat",
  "fk": "BLIBLI",
  "fl": "RummyLoot",
  "fm": "Touchance",
  "fo": "MobiKwik",
  "fr": "Dana",
  "fs": "Şikayet var",
  "ft": "Букмекерские",
  "fu": "Snapchat",
  "fv": "Vidio",
  "fw": "99acres",
  "fx": "PGbonus",
  "fy": "Mylove",
  "fz": "KFC",
  "ga": "Roposo",
  "gb": "YouStar",
  "gc": "TradingView",
  "gd": "Surveytime",
  "ge": "Paytm",
  "gf": "GoogleVoice",
  "gg": "PagSmile",
  "gh": "GyFTR",
  "gi": "Hotline",
  "gj": "Carousell",
  "gk": "AptekaRU",
  "gl": "GlobalTel",
  "gm": "Mocospace",
  "go": "Google,youtube,Gmail",
  "gp": "Ticketmaster",
  "gq": "Freelancer",
  "gr": "Astropay",
  "gs": "SamsungShop",
  "gt": "Gett",
  "gu": "Fora",
  "gv": "Humta",
  "gw": "CallApp",
  "gx": "Hepsiburadacom",
  "gz": "LYKA",
  "ha": "My11Circle",
  "hb": "Twitch",
  "hc": "MOMO",
  "he": "Mewt",
  "hg": "Switips",
  "hh": "Uplay",
  "hi": "JungleeRummy",
  "hj": "Nykaa",
  "hk": "4Fun",
  "hl": "Band",
  "hm": "Globus",
  "hn": "Bonia",
  "ho": "Cathay",
  "hp": "Meesho",
  "hq": "Magicbricks",
  "hr": "JKF",
  "hs": "Asda",
  "hu": "Ukrnet",
  "hw": "Alipay/Alibaba",
  "hx": "AliExpress",
  "hy": "Ininal",
  "hz": "Drom",
  "ia": "Socios",
  "ib": "Immowelt",
  "ic": "JoGo",
  "ie": "Bet365",
  "ig": "Instagram",
  "ih": "TeenPattiStarpro",
  "ii": "CashKaro",
  "ij": "Revolut",
  "ik": "GuruBets",
  "il": "IQOS",
  "im": "Imo",
  "io": "ЗдравСити",
  "ip": "Burger King",
  "iq": "Icq",
  "ir": "Chispa",
  "it": "CashApp",
  "iu": "Bykea",
  "iv": "Inboxlv",
  "iw": "MyLavash",
  "ix": "Celcoin",
  "iy": "FoodHub",
  "iz": "Global24",
  "ja": "Weverse",
  "jb": "Wing Money",
  "jd": "GiraBank",
  "je": "Nanovest",
  "jf": "Likee",
  "jg": "Grab",
  "jh": "PingPong",
  "ji": "Monobank",
  "jj": "Aitu",
  "jl": "Hopi",
  "jm": "Mzadqatar",
  "jn": "CloudBet",
  "jo": "SticPay",
  "jp": "Rbt",
  "jq": "Paysafecard",
  "jr": "Самокат",
  "js": "GolosZa",
  "jt": "TurkiyePetrolleri",
  "ju": "Indomaret",
  "jv": "Consultant",
  "jw": "Br777",
  "jx": "Swiggy",
  "jy": "Sorare",
  "jz": "Kaya",
  "ka": "Shopee",
  "kb": "Kufarby",
  "kc": "Vinted",
  "kd": "Author24",
  "ke": "Эльдорадо",
  "kf": "Weibo",
  "kg": "FreeChargeApp",
  "kh": "Bukalapak",
  "ki": "99app",
  "kj": "YAPPY",
  "kk": "Idealista",
  "kl": "Kolesa.kz",
  "km": "Rozetka",
  "kn": "Verse",
  "kp": "HQ Trivia",
  "kq": "FotoCasa",
  "kr": "Eyecon",
  "ks": "Hirect",
  "kt": "KakaoTalk",
  "ku": "RoyalWin",
  "kv": "Rush",
  "kw": "Foody",
  "kx": "Vivo",
  "ky": "SpatenOktoberfest",
  "kz": "NimoTV",
  "la": "Ssoidnet",
  "lb": "Mailru Group",
  "lc": "Subito",
  "ld": "Cashmine",
  "le": "E bike Gewinnspiel",
  "lf": "TikTok/Douyin",
  "lg": "MediBuddy",
  "lh": "24betting",
  "li": "Baidu",
  "lj": "Santander",
  "lk": "PurePlatfrom",
  "ll": "888casino",
  "lm": "FarPost",
  "ln": "Grofers",
  "lo": "OPPO",
  "lp": "Algida",
  "lq": "Potato",
  "lr": "Okta",
  "ls": "Careem",
  "lt": "BitClout",
  "lu": "Crickpe",
  "lv": "Megogo",
  "lw": "MrGreen",
  "lx": "DewuPoison",
  "ly": "Olacabs",
  "lz": "Things",
  "ma": "Mail.ru",
  "mb": "Yahoo",
  "mc": "Michat",
  "md": "Банки",
  "me": "Line msg",
  "mf": "Weidian",
  "mg": "Magnit",
  "mh": "Ашан",
  "mi": "Zupee",
  "mj": "Zalo",
  "mk": "LongHu",
  "ml": "ApostaGanha",
  "mm": "Microsoft",
  "mn": "RRSA",
  "mo": "Bumble",
  "mp": "Winmasters",
  "mq": "GMNG",
  "mr": "Fastmail",
  "ms": "NovaPoshta",
  "mt": "Steam",
  "mu": "MyMusicTaste",
  "mv": "Fruitz",
  "mw": "Transfergo",
  "mx": "SoulApp",
  "my": "CAIXA",
  "mz": "Zolushka",
  "nb": "Верный",
  "nc": "Payoneer",
  "ne": "Coindcx",
  "nf": "Netflix",
  "ng": "FunPay",
  "nh": "AlloBank",
  "ni": "Gojek",
  "nj": "FreshKarta",
  "nk": "Gittigidiyor",
  "nl": "Myntra",
  "nm": "Thisshop",
  "nn": "Giftcloud",
  "no": "Virgo",
  "np": "Siply",
  "nq": "Trip",
  "nr": "Tosla",
  "ns": "Oldubil",
  "nt": "Sravni",
  "nu": "Stripe",
  "nv": "Naver",
  "nw": "Ximalaya",
  "ny": "BitcoinBon",
  "nz": "Foodpanda",
  "ob": "Onlinerby",
  "oc": "DealShare",
  "od": "FWDMAX",
  "oe": "Codashop",
  "of": "Urent/jet/RuSharing",
  "og": "Okko",
  "oh": "MapleSEA",
  "oi": "Tinder",
  "oj": "LoveRu",
  "ok": "Ok.ru",
  "ol": "KazanExpress",
  "om": "Corona",
  "oo": "LigaPro",
  "op": "MIRATORG",
  "oq": "Vlife",
  "os": "Dhani",
  "ot": "Any other",
  "ou": "Gabi",
  "ov": "Beget",
  "ow": "RegRu",
  "ox": "Damejidlo",
  "oy": "CashFly",
  "oz": "Poshmark",
  "pa": "Gamekit",
  "pb": "SkyTV",
  "pc": "Casino/bet/gambling",
  "pd": "IFood",
  "pf": "Pof.com",
  "pg": "NRJ Music Awards",
  "ph": "SnappFood",
  "pj": "Podeli",
  "pl": "Perekrestok",
  "pm": "AOL",
  "pn": "CoffeeLike",
  "po": "Premium.one",
  "pp": "Huya",
  "pq": "CDkeys",
  "pr": "Trendyol",
  "ps": "Zdorov",
  "pt": "Bitaqaty",
  "pv": "Koshelek",
  "pw": "SellMonitor",
  "px": "Nifty",
  "py": "Monese",
  "pz": "Lidl",
  "qa": "MyFishka",
  "qb": "Payberry",
  "qc": "Праймериз 2020",
  "qd": "Taobao",
  "qe": "GG",
  "qf": "RedBook",
  "qg": "MoneyPay",
  "qh": "Oriflame",
  "qi": "23red",
  "qj": "Whoosh",
  "qk": "Bit",
  "ql": "CMTcuzdan",
  "qm": "RosaKhutor",
  "qn": "Blued",
  "qo": "Moneylion",
  "qp": "Максавит",
  "qq": "Tencent QQ",
  "qr": "MEGA",
  "qs": "МирЗнакомств",
  "qt": "MoneyСontrol",
  "qu": "Agroinform",
  "qv": "Badoo",
  "qw": "Qiwi",
  "qx": "WorldRemit",
  "qy": "Zhihu",
  "qz": "Faceit",
  "ra": "KeyPay",
  "rb": "Tick",
  "rc": "Skype",
  "rd": "Lenta",
  "re": "Coinbase",
  "rf": "Akudo",
  "rg": "Porbet",
  "rh": "Ace2Three",
  "ri": "BillMill",
  "rj": "Детский мир",
  "rk": "Fotka",
  "rl": "InDriver",
  "rn": "Neftm",
  "ro": "PingCode",
  "rp": "Hamrahaval",
  "rq": "AptekiPlus",
  "rr": "Wolt",
  "rs": "Lotus",
  "rt": "Hily",
  "ru": "HOP",
  "rv": "Kotak811",
  "rx": "Sheerid",
  "ry": "McDonalds",
  "rz": "EasyPay",
  "sa": "AGIBANK",
  "sb": "Lamoda",
  "sc": "Voggt",
  "sd": "Dodopizza",
  "sf": "SneakersnStuff",
  "sg": "OZON",
  "sh": "Vkusvill",
  "si": "Cita Previa",
  "sj": "HandyPick",
  "sk": "Skroutz",
  "sl": "Robota.ua",
  "sm": "YoWin",
  "sn": "OLX",
  "so": "RummyWealth",
  "sp": "HappyFresh",
  "sq": "KuCoinPlay",
  "sr": "Starbucks",
  "ss": "Hezzl",
  "st": "Auchan",
  "su": "LOCO",
  "sv": "Dostavista",
  "sw": "NCsoft",
  "sy": "Brahma",
  "sz": "Pivko24",
  "ta": "Wink",
  "tc": "Rambler",
  "td": "ChaingeFinance",
  "te": "EFood",
  "tf": "Noon",
  "tg": "Telegram",
  "th": "WestStein",
  "ti": "Cryptocom",
  "tj": "DbrUA",
  "tk": "МВидео",
  "tl": "Truecaller",
  "tm": "Akulaku",
  "tn": "LinkedIN",
  "tp": "IndiaGold",
  "tq": "Swvl",
  "tr": "Paysend",
  "ts": "PayPal",
  "tt": "Ziglu",
  "tu": "Lyft",
  "tv": "Flink",
  "tw": "Twitter",
  "tx": "Bolt",
  "ty": "Окей",
  "tz": "Лейка",
  "ua": "BlaBlaCar",
  "ub": "Uber",
  "uc": "Tatneft",
  "ud": "Disney Hotstar",
  "ue": "Onet",
  "uf": "Eneba",
  "ug": "Fiqsy",
  "uh": "Yubo",
  "ui": "RuTube",
  "uj": "СhampionСasino",
  "uk": "Airbnb",
  "ul": "Getir",
  "um": "Belwest",
  "un": "Humblebundle",
  "uo": "CafeBazaar",
  "uq": "TopDetal",
  "ur": "MyDailyCash",
  "us": "IRCTC",
  "ut": "Энергобум",
  "uu": "Wildberries",
  "uv": "BinBin",
  "uw": "Kirana",
  "ux": "Домовой",
  "uy": "Meliuz",
  "uz": "OffGamers",
  "va": "SportGully",
  "vb": "Кораблик",
  "vc": "Banqi",
  "vd": "Betfair",
  "ve": "Dream11",
  "vf": "Q12 Trivia",
  "vg": "ShellBox",
  "vh": "Штолле",
  "vi": "Viber",
  "vj": "Stormgain",
  "vk": "Vk.com",
  "vl": "Ортека",
  "vm": "OkCupid",
  "vn": "Yaay",
  "vo": "Brand20ua",
  "vp": "Kwai",
  "vq": "LadyMaria",
  "vr": "MotorkuX",
  "vs": "WinzoGame",
  "vt": "Innomax",
  "vv": "Seosprint",
  "vw": "CoinField",
  "vx": "HeyBox",
  "vy": "Meta",
  "vz": "Hinge",
  "wa": "Whatsapp",
  "wb": "WeChat",
  "wc": "Craigslist",
  "wd": "Столото",
  "we": "DrugVokrug",
  "wf": "YandexGo",
  "wg": "Skout",
  "wh": "TanTan",
  "wj": "1хbet",
  "wk": "Mobile01",
  "wl": "YouGotaGift",
  "wm": "99Speed",
  "wn": "GameArena",
  "wo": "Parkplus",
  "wp": "163СOM",
  "wr": "Walmart",
  "ws": "Feeld",
  "wt": "IZI",
  "wu": "PrivetMir",
  "wv": "AIS",
  "ww": "BIP",
  "wx": "Apple",
  "wy": "Yami",
  "wz": "FoxFord",
  "xa": "УлыбкаРадуги",
  "xb": "RummyOla",
  "xc": "SynotTip",
  "xd": "Tokopedia",
  "xe": "GalaxyChat",
  "xf": "LightChat",
  "xg": "FortunaSK",
  "xh": "OVO",
  "xi": "InFund",
  "xj": "White Calling",
  "xk": "DiDi",
  "xl": "Wmaraci",
  "xm": "Лэтуаль",
  "xn": "Familia",
  "xo": "Notifire",
  "xp": "MonetaRu",
  "xq": "MPL",
  "xr": "Tango",
  "xs": "GroupMe",
  "xt": "Flipkart",
  "xu": "RecargaPay",
  "xv": "Wish",
  "xw": "Taki",
  "xx": "Joyride",
  "xy": "Depop",
  "xz": "Paycell",
  "ya": "Yandex/Uber",
  "yb": "Система Город",
  "yd": "米画师Mihuashi",
  "ye": "ZaleyCash",
  "yf": "Citymobil",
  "yg": "CourseHero",
  "yh": "Hh",
  "yi": "Yemeksepeti",
  "yj": "EWallet",
  "yk": "СпортМастер",
  "yl": "Yalla",
  "ym": "Youla.ru",
  "yn": "Allegro",
  "yo": "Amasia",
  "yp": "Payzapp",
  "yq": "Mail.com",
  "ys": "ZCity",
  "yu": "Xiaomi",
  "yv": "IPLwin",
  "yw": "Grindr",
  "yx": "JTExpress",
  "yy": "Venmo",
  "yz": "Около",
  "za": "JDcom",
  "zb": "FreeNow",
  "zd": "Zilch",
  "ze": "Shpock",
  "zf": "OnTaxi",
  "zg": "Setel",
  "zh": "Zoho",
  "zi": "LoveLocal",
  "zj": "ROBINHOOD",
  "zk": "Deliveroo",
  "zl": "Airtel",
  "zm": "OfferUp",
  "zn": "Biedronka",
  "zo": "Kaggle",
  "zp": "Pinduoduo",
  "zq": "IndiaPlays",
  "zr": "Papara",
  "zs": "Bilibili",
  "zt": "Budweiser",
  "zu": "BigC",
  "zv": "Digikala",
  "zw": "Quack",
  "zx": "CommunityGaming",
  "zy": "Nttgame",
  "zz": "Dent",
};

/**
 * Retorna o nome legível de um serviço a partir do código
 * @param code Código do serviço (ex: "wa", "tg", "go")
 * @returns Nome do serviço ou fallback "Service CODE"
 */
export function getServiceName(code: string): string {
  const normalizedCode = code.toLowerCase().trim();
  return SERVICE_NAMES[normalizedCode] || `Service ${code.toUpperCase()}`;
}
